version: "3.9"

services:
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${PWD}/:/app  # mount the source volume